version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: sem_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    logging:
        driver: "json-file"
        options:
            max-size: "10k"
            max-file: "10"
    volumes:
      - ./share/elasticsearch:/home/elk
      - ./common/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: sem_kibana
    restart: always
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./share/kibana:/home/elk
      - ./common/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
  logstash:
    build:
      context: .
      dockerfile: Dockerfile-logstash
    container_name: sem_logstash
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./share/logstash:/home/elk
      - ./common/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./common/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./common/logstash/pipeline:/usr/share/logstash/pipeline